// src/vue/component/Category.vue
<template>
<div class="category">
  <h2>{{ categoryName }}</h2>
  <div class="items">
    <table>
      <thead>
        <tr>
          <th>項目</th>
          <th class="item-volume">数量</th>
          <th class="item-unit_cost">単価</th>
          <th class="item-total_cost">費用</th>
        </tr>
      </thead>
      <tbody>
        <Item
          v-for="item in items"
          :content="item"
          :onChangeVolume="onChangeVolume"
          :key="item.id"
        />
      </tbody>
    </table>
  </div>
</div>
</template>
<script>
import Item from './Item'

export default {
  props: {
    categoryName: {
      type: String,
      required: true
    },
    items: {
      type: Array,
      required: true
    },
    onChangeVolume: {
      type: Function,
      required: true
    }
  },
  components: {
    Item
  }
}
</script>

// src/react/component/Category.jsx
import * as React from 'react'
import Item from './Item'

export default class Category extends React.Component {
  render () {
    const items = this.props.items.map(item => (
      <Item
        key={item.id}
        content={item}
        onChangeVolume={this.props.onChangeVolume}
      />
    ))

    return (
      <div className="category">
        <h2>{this.props.categoryName}</h2>
        <div className="items">
          <table>
            <thead>
              <tr>
                <th>項目</th>
                <th className="item-volume">数量</th>
                <th className="item-unit_cost">単価</th>
                <th className="item-total_cost">費用</th>
              </tr>
            </thead>
            <tbody>
              { items }
            </tbody>
          </table>
        </div>
      </div>
    )
  }
}
