// src/vue/component/Item.vue
<template>
<tr :key="content.id" :class="{'is-edited': totalCost !== 0}">
  <td>{{ content.subject }}</td>
  <td class="text-center">
    <input
      type="number"
      :value="content.volume"
      @input="onInput"
      min="0"
    >
  </td>
  <td class="text-center">{{ content.cost.toLocaleString() }}</td>
  <td class="text-center">{{ tweenTotalCost.toLocaleString() }}</td>
</tr>
</template>
<script>
import TweenLite from 'gsap/TweenLite'

export default {
  data () {
    return {
      tweenTotalCost: 0,
      volume: this.content.volume
    }
  },
  watch: {
    totalCost (next, prev) {
      const self = this

      const obj = {
        val: prev
      }

      TweenLite.to(obj, 0.3, {
        val: next,
        onUpdate () {
          self.tweenTotalCost = Math.floor(obj.val)
        }
      })
    }
  },
  methods: {
    onInput (event) {
      const val = parseInt(event.currentTarget.value, 10)

      if (typeof val !== 'number' || isNaN(val)) {
        this.volume = 0
        this.onChangeVolume(this.content.id, 0)
        return
      }

      this.volume = val
      this.onChangeVolume(this.content.id, val)
    }
  },
  computed: {
    totalCost () {
      return this.content.volume * this.content.cost
    }
  },
  props: {
    content: {
      type: Object,
      required: true
    },
    onChangeVolume: {
      type: Function,
      required: true
    }
  }
}
</script>

// src/react/component/Item.jsx
import * as React from 'react'
import TweenLite from 'gsap/TweenLite'
import config from '../../config.json'

export default class Item extends React.Component {
  constructor (props) {
    super(props)

    this.onChange = this.onChange.bind(this)
    this.state = {
      tweenTotalCost: 0
    }
  }

  onChange (event) {
    const nextValue = parseInt(event.currentTarget.value, 10)

    if (typeof nextValue !== 'number' || isNaN(nextValue)) {
      this.props.onChangeVolume(this.props.content.id, 0)
      return
    }

    this.props.onChangeVolume(this.props.content.id, nextValue)
  }

  componentDidUpdate (prevProps) {
    if (prevProps.content.volume !== this.props.content.volume) {
      const self = this
      const obj = {
        val: prevProps.content.volume
      }

      TweenLite.to(obj, config.duration, {
        val: this.props.content.volume,
        onUpdate () {
          self.setState({
            tweenTotalCost: Math.floor(obj.val * self.props.content.cost)
          })
        }
      })
    }
  }

  shouldComponentUpdate (nextProps, nextState) {
    const hasChangedProps = nextProps.content.volume !== this.props.content.volume
    const hasChangedState = nextState.tweenTotalCost !== this.state.tweenTotalCost

    if (hasChangedProps || hasChangedState) {
      return true
    }

    return false
  }

  rowClassName () {
    return this.props.content.volume ? 'is-edited' : ''
  }

  render () {
    return (
      <tr className={this.rowClassName()}>
        <td>{ this.props.content.subject }</td>
        <td className="text-center">
          <input
            type="number"
            value={this.props.content.volume}
            min="0"
            onInput={this.onChange}
          />
        </td>
        <td className="text-center">{ this.props.content.cost.toLocaleString() }</td>
        <td className="text-center">{ this.state.tweenTotalCost.toLocaleString() }</td>
      </tr>
    )
  }
}
