// src/vue/Item.vue
<template>
<tr :key="item.id" :class="{'is-edited': totalCost !== 0}">
  <td>{{ item.subject }}</td>
  <td class="text-center"><input type="number" v-model.number="item.volume" min="0"></td>
  <td class="text-center">{{ item.cost.toLocaleString() }}</td>
  <td class="text-center">{{ tweenTotalCost }}</td>
</tr>
</template>
<script>
import TweenLite from 'gsap/TweenLite'

export default {
  data () {
    return {
      tweenTotalCost: '0'
    }
  },
  watch: {
    totalCost (next, prev) {
      const self = this

      const obj = {
        val: prev
      }

      TweenLite.to(obj, 0.3, {
        val: next,
        onUpdate () {
          self.tweenTotalCost = Math.floor(obj.val).toLocaleString()
        }
      })
    }
  },
  computed: {
    totalCost () {
      return this.item.volume * this.item.cost * this.item.man_hour
    }
  },
  props: {
    item: {
      type: Object,
      required: true
    }
  }
}
</script>

// src/react/component/Item.jsx
import * as React from 'react'
import TweenLite from 'gsap/TweenLite'
import config from '../../config.json'

export default class Item extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      tweenTotalCost: 0
    }
  }

  onChange (id, event) {
    event.preventDefault()

    const prevVal = this.props.content.volume
    const nextVal = parseInt(event.currentTarget.value, 10)

    const self = this
    const obj = {
      val: prevVal
    }

    TweenLite.to(obj, config.duration, {
      val: nextVal,
      onUpdate () {
        self.setState({
          tweenTotalCost: Math.floor(obj.val * self.props.content.cost * self.props.content.man_hour)
        })
      }
    })

    this.props.onChangeVolume(id, nextVal)
  }

  rowClassName () {
    return this.props.content.volume ? 'is-edited' : ''
  }

  render () {
    return (
      <tr className={this.rowClassName()}>
        <td>{ this.props.content.subject }</td>
        <td className="text-center">
          <input
            type="number"
            value={this.props.content.volume}
            min="0"
            onChange={(event) => this.onChange(this.props.content.id, event)}
          />
        </td>
        <td className="text-center">{ this.props.content.cost.toLocaleString() }</td>
        <td className="text-center">{ this.state.tweenTotalCost.toLocaleString() }</td>
      </tr>
    )
  }
}
